### ISSUE TITLE
Doesnt function after Universe update.

### ISSUE THREAD

**Issue by scriptuser123** [momocow/OGame-Redesign-v.6-Auction-Timer#10]
The auction timer doesnt work anymore. Tried to reinstall. No effect. There has been an update shortly prior.
Other scripts are rendered unfunctional since the update as well.

**Comment by momocow** [comment]
Yes, it does not work since OGame v7 which is also a breaking change to the game itself and you are the first one to issue an update. :)

I will check it asap.

**Comment by momocow** [comment]
Fixed by f127ec80.

You can visit the following link to update your script.

https://github.com/momocow/OGame-Redesign-v.6-Auction-Timer/raw/5cc34d2e1e04200e9ed94aec997ee96afd17531a/dist/auction-timer.user.js

**Comment by scriptuser123** [comment]
Thank you.

Am Mo., 14. Sept. 2020 um 17:35 Uhr schrieb 牛牛 <notifications@github.com>:
